// ─────────────────────────────────────────────────────────────────────────────
// Curriculum types — level → lesson → unit → activity stream.
//
// A *unit* is the completable study session (5–8 words, 5–8 minutes). A unit's
// activity stream is built at runtime by `buildActivityStream`; nothing here is
// persisted beyond the generated unit table in `src/data/units/`.
//
// Every activity carries exactly the payload its screen needs, modelled from
// the approved design files in `design/`:
//   WordCard.dc.html → word-intro      Writing.dc.html → hanzi-write
//   Activity.dc.html → roleplay        Path.dc.html    → unit shape + ordering
// ─────────────────────────────────────────────────────────────────────────────

export type HskLevelNo = 1 | 2 | 3

/**
 * Composite address of a unit. Lesson ids collide across levels
 * (HSK1 1..15, HSK2 1..15, HSK3 1..18), so `level` is never optional.
 */
export interface UnitRef {
  level: HskLevelNo
  /** Lesson id as it appears in that level's `lessons[].id`. */
  lesson: number
  /** 1-based ordinal of the unit inside its lesson. */
  unit: number
}

/** Stable string key for a UnitRef — safe as a React key, map key or DB key. */
export type UnitKey = `${HskLevelNo}:${number}:${number}`

export function unitKey(ref: UnitRef): UnitKey {
  return `${ref.level}:${ref.lesson}:${ref.unit}`
}

export function parseUnitKey(key: string): UnitRef | null {
  const m = /^([123]):(\d+):(\d+)$/.exec(key)
  if (!m) return null
  return { level: Number(m[1]) as HskLevelNo, lesson: Number(m[2]), unit: Number(m[3]) }
}

export function sameUnit(a: UnitRef, b: UnitRef): boolean {
  return a.level === b.level && a.lesson === b.lesson && a.unit === b.unit
}

// ── Unit ────────────────────────────────────────────────────────────────────

/**
 * One topical unit cut out of a lesson. Generated by `scripts/build-units.js`
 * into `src/data/units/units.generated.ts` — do not hand-edit that file.
 */
export interface Unit {
  ref: UnitRef
  /** `${level}:${lesson}:${unit}` — duplicated onto the record for cheap lookup. */
  key: UnitKey
  /** Arabic title, derived from the unit's own words. */
  title: string
  /** The same title in English. Both languages, always — see [4.6]. */
  titleEn: string
  /** One-line Arabic goal, derived from the unit's own words. */
  goal: string
  /** Vocabulary ids owned by this unit. Every lesson word lands in exactly one. */
  wordIds: number[]
  /** Grammar rule ids the unit may draw a `grammar-brief` from. */
  grammarIds: number[]
  /** Indices into `lesson.keySentences` this unit's words actually appear in. */
  keySentenceIndices: number[]
  /** Ids of `conversations` (level-scoped) whose turns use this unit's words. */
  conversationIds: number[]
  /** True for the last unit of its lesson — it carries the lesson's exam items. */
  carriesExam: boolean
  /** Hanzi characters introduced by this unit's words, in first-appearance order. */
  hanzi: string[]
}

// ── Activities ──────────────────────────────────────────────────────────────

/**
 * The 17 library sections, re-cast as drills inside a unit.
 * See the plan's «كل قسم من الـ١٧ يصير نوع نشاط داخل الوحدة» table.
 */
export type ActivityKind =
  | 'explanation'        // الشرح: the teaching card that opens a group
  | 'word-intro'         // المفردات — تعرّف: the six-stage new-word card
  | 'word-recall'        // المفردات — استدعاء: recognition/production recall
  | 'hanzi-write'        // الحروف: trace the character in stroke order
  | 'tone-discriminate'  // البينين: pick the tone you heard / that fits
  | 'pinyin-match'       // البينين: match syllable ↔ character
  | 'pronounce'          // تدريب النطق: say it, get scored
  | 'image-match'        // القاموس البصري: picture ↔ word
  | 'grammar-brief'      // القواعد: the micro-explanation
  | 'grammar-apply'      // القواعد: apply it immediately
  | 'sentence-order'     // الجمل: reorder tokens into a sentence
  | 'fill-blank'         // الجمل: fill the gap
  | 'translate'          // الجمل: translate both directions
  | 'roleplay'           // المحادثات: choose the speaker's reply
  | 'story-excerpt'      // القصص: passage + comprehension question
  | 'daily-qa'           // أسئلة يومية: a life question with a model answer
  | 'game-break'         // الألعاب: the every-six-activities breather
  | 'exam-style'         // محاكي الامتحان: HSK-format items closing the lesson

/** Where an activity sits on the recognition → production ramp. */
export type ActivityMode = 'present' | 'recognise' | 'produce' | 'break'

/**
 * [4.2] A string the learner reads, in both languages.
 *
 * The activity engine used to build its user-facing copy as bare Arabic
 * template literals — «النبرة ٣», «بماذا يردّ ليلى؟», «اكتب من الأعلى إلى
 * الأسفل» — eleven of them, reaching seven of the seventeen activity kinds.
 * There was no `locale` anywhere in the engine to consult, so an English
 * learner met Arabic instructions on every tone drill, every role-play and
 * every writing board.
 *
 * Both languages travel together in the payload rather than the engine taking a
 * locale, which keeps `buildActivityStream` pure and lets ONE built stream serve
 * both routes.
 */
export interface Bilingual {
  ar: string
  en: string
}

/** Pick the reader's side of a bilingual string. */
export function say(text: Bilingual, locale: 'ar' | 'en'): string {
  return locale === 'en' ? text.en : text.ar
}

// ── [2.1] The explanation ───────────────────────────────────────────────────

/** One worked example. Both languages, always — see [4.6]. */
export interface ExplanationExample {
  zh: string
  pinyin: string
  ar: string
  en: string
}

/**
 * A mistake learners actually make, and what to do instead.
 *
 * Not decoration. Naming the wrong form beside the right one is what stops a
 * learner inventing «我是很好» from an English habit; a rule stated only in the
 * positive leaves every wrong path equally plausible.
 */
export interface CommonMistake {
  /** The wrong form, as a learner would write it. */
  wrongZh: string
  /** The corrected form. */
  rightZh: string
  whyAr: string
  whyEn: string
}

/** Why the engine emitted this activity — drives copy and progress weighting. */
export type ActivitySource =
  /** First encounter with a word of this unit. */
  | 'new'
  /** Practice of a word this unit owns. */
  | 'practice'
  /** SRS review pulled in from an earlier unit. */
  | 'review'
  /** Extra repetition because the learner has missed this word. */
  | 'remediation'
  /** Lesson-closing assessment. */
  | 'assessment'

export interface ActivityBase {
  /** Deterministic id: `${unitKey}#${index}-${kind}`. Stable for a given seed. */
  id: string
  kind: ActivityKind
  mode: ActivityMode
  source: ActivitySource
  unit: UnitRef
  /** Words this activity exercises — what SRS should be graded against. */
  wordIds: number[]
  /** 0-based position in the stream. */
  index: number
}

// ── Shared payload fragments ────────────────────────────────────────────────

export interface SentenceRef {
  zh: string
  pinyin: string
  ar: string
}

export interface RadicalPart {
  char: string
  /** Arabic gloss of the component, empty when the source data has none. */
  meaning: string
}

/** A choice in any multiple-choice drill. */
export interface Choice {
  /** Primary label — Chinese, pinyin or Arabic depending on the drill. */
  label: string
  /**
   * The label in English, where it differs.
   *
   * Most choices are Chinese or pinyin and read the same on both routes, so
   * this is absent for them. It exists for the few whose label is prose — the
   * exam's «✓ صحيح / ✗ خطأ» being the case that forced it.
   *
   * NOT YET COVERED, and it is a content gap rather than a wiring one: a
   * `translate` drill in the zh→ar direction labels its options with the
   * sentence's Arabic, and the corpus has no English for 1,890 of those
   * sentences. Those options stay Arabic on the English route until the
   * translations are authored; `audit-content.js` counts them.
   */
  labelEn?: string
  /** Optional secondary line under the label (design shows both). */
  sub?: string
  /** Word id behind this choice, when the choice is a vocabulary word. */
  wordId?: number
}

export interface MultipleChoice {
  choices: Choice[]
  /** Index into `choices`. */
  correct: number
  /**
   * Explanation shown in the verdict bar — always present.
   *
   * `en` may be empty where the SOURCE DATA has no English (the HSK1 exam
   * bank's explanations are Arabic-only, and 1,079 mnemonics have no English
   * field at all). The view falls back to the Arabic in that case rather than
   * showing an empty verdict: a learner who has just answered deserves to be
   * told why, and a wrong-language reason beats no reason. The gap is content,
   * counted by `audit-content.js`, and closes as the English is authored.
   */
  explanation: Bilingual
}

// ── One interface per kind ──────────────────────────────────────────────────

/**
 * THE TEACHING CARD. [2.1]
 *
 * The platform had none. Every one of the seventeen kinds below asks the
 * learner for something; not one of them told them anything first. That is the
 * gap the owner named — «تمرين بلا تدريس» — and it is the difference between a
 * lesson and a quiz.
 *
 * It carries what an explanation needs and nothing that belongs to a drill:
 * the idea in one paragraph, worked examples in both languages, the mistakes
 * learners actually make, and a single line to carry away. No answer, no
 * scoring, no verdict — a learner cannot get an explanation wrong.
 */
export interface ExplanationActivity extends ActivityBase {
  kind: 'explanation'
  /** What this card teaches: a grammar rule, or the unit's new vocabulary. */
  topic: 'grammar' | 'vocabulary' | 'pronunciation' | 'writing'
  /** Set when `topic` is 'grammar'. */
  grammarId?: number
  titleAr: string
  titleEn: string
  /** The idea, in a paragraph a beginner can hold. */
  ideaAr: string
  ideaEn: string
  /** The shape, e.g. «فاعل + 是 + اسم». */
  patternAr: string
  patternEn: string
  examples: ExplanationExample[]
  mistakes: CommonMistake[]
  /** One line to carry away. */
  summaryAr: string
  summaryEn: string
  /**
   * Whether a human has signed off on the authored parts.
   *
   * The owner's rule: anything the machine wrote waits for review. This travels
   * with the content so a screen can mark it and a report can count it.
   */
  status: 'authored' | 'needs_review'
}

/** WordCard.dc.html — the six stages: see it, hear it, break it down,
 *  mnemonic, write it, use it. */
export interface WordIntroActivity extends ActivityBase {
  kind: 'word-intro'
  word: {
    id: number
    zh: string
    pinyin: string
    meaning: string
    /** Tone number per syllable, e.g. [1, 2] for Zhōngguó. */
    tones: number[]
    strokeCount: number
  }
  /** Components with Arabic glosses — the «من أي شيء يتكوّن» row. */
  parts: RadicalPart[]
  /** Arabic memory hook; empty string when the source data has none. */
  mnemonic: string
  /** The «في جملة» block. */
  example: SentenceRef | null
  /** Ordinal within the unit's new words, for «٣ من ٨ كلمات». */
  wordOrdinal: number
  wordTotal: number
}

/** Recall drill. `direction` decides which side is the prompt. */
export interface WordRecallActivity extends ActivityBase {
  kind: 'word-recall'
  direction: 'zh-to-ar' | 'ar-to-zh' | 'audio-to-zh'
  prompt: string
  promptSub?: string
  question: MultipleChoice
}

/** Writing.dc.html — one character on the tracing board. */
export interface HanziWriteActivity extends ActivityBase {
  kind: 'hanzi-write'
  char: string
  strokeCount: number
  /** Word the character was met in, for the heading. */
  inWord: { zh: string; pinyin: string; meaning: string }
  /** Components, for the stroke-rule hint. */
  parts: RadicalPart[]
  /** Hint under the board. */
  hint: Bilingual
}

export interface ToneDiscriminateActivity extends ActivityBase {
  kind: 'tone-discriminate'
  /** The syllable in question, without its tone mark. */
  syllable: string
  /** The target rendered with its mark, e.g. "mā". */
  target: string
  /** Which of the four tones is correct (1–4). */
  correctTone: 1 | 2 | 3 | 4
  /** Four candidate readings of the same syllable. */
  question: MultipleChoice
}

export interface PinyinMatchActivity extends ActivityBase {
  kind: 'pinyin-match'
  /** Left column: characters. Right column: pinyin. Match by index in `pairs`. */
  pairs: { wordId: number; zh: string; pinyin: string; meaning: string }[]
}

export interface PronounceActivity extends ActivityBase {
  kind: 'pronounce'
  targetZh: string
  targetPinyin: string
  meaning: string
  /** 'word' reads a single item, 'sentence' reads a full key sentence. */
  scope: 'word' | 'sentence'
  /** Similarity score (0–100) required to pass. */
  passScore: number
}

export interface ImageMatchActivity extends ActivityBase {
  kind: 'image-match'
  /** Emoji standing in for the picture, from the visual dictionary. */
  emoji: string
  /** Arabic category label the emoji came from. */
  category: string
  question: MultipleChoice
}

export interface GrammarBriefActivity extends ActivityBase {
  kind: 'grammar-brief'
  grammarId: number
  titleAr: string
  /** Arabic explanation. */
  description: string
  /** Arabic pattern line, e.g. «فاعل + فعل + مفعول». */
  pattern: string
  examples: SentenceRef[]
}

export interface GrammarApplyActivity extends ActivityBase {
  kind: 'grammar-apply'
  grammarId: number
  /** Instruction line. */
  prompt: Bilingual
  question: MultipleChoice
}

export interface SentenceOrderActivity extends ActivityBase {
  kind: 'sentence-order'
  /** Tokens shuffled for display; `correctOrder` indexes back into them. */
  tokens: string[]
  correctOrder: number[]
  sentence: SentenceRef
}

export interface FillBlankActivity extends ActivityBase {
  kind: 'fill-blank'
  /** Sentence with the gap marked by `____`. */
  masked: string
  pinyin: string
  ar: string
  question: MultipleChoice
}

export interface TranslateActivity extends ActivityBase {
  kind: 'translate'
  direction: 'zh-to-ar' | 'ar-to-zh'
  prompt: string
  promptSub?: string
  question: MultipleChoice
}

/** Activity.dc.html — one conversation turn, learner picks the reply. */
export interface RoleplayActivity extends ActivityBase {
  kind: 'roleplay'
  conversationId: number
  /** Arabic scene line. */
  scene: string
  /** Instruction, e.g. «بماذا تجيب ليلى؟» / "What does Laila reply?". */
  prompt: Bilingual
  /** The turn the learner is answering. */
  cue: SentenceRef & { speaker: string }
  question: MultipleChoice
}

export interface StoryExcerptActivity extends ActivityBase {
  kind: 'story-excerpt'
  storyId: number
  titleAr: string
  /** Two to four consecutive lines of the story. */
  lines: SentenceRef[]
  question: MultipleChoice
}

export interface DailyQaActivity extends ActivityBase {
  kind: 'daily-qa'
  /**
   * The question put to the learner, in Chinese.
   *
   * Named `ask`, not `question`: on every other kind `question` is the
   * `MultipleChoice` the learner answers, and one field name meaning two
   * different shapes is how a renderer ends up reading `.choices` off a
   * sentence and showing an empty answer list.
   */
  ask: SentenceRef
  /** A model answer the learner compares against. */
  modelAnswer: SentenceRef
  /** Nudge on how to adapt it. */
  hint: Bilingual
}

export type GameId = 'match' | 'memory' | 'tone-catch' | 'speed-recall'

export interface GameBreakActivity extends ActivityBase {
  kind: 'game-break'
  game: GameId
  /** Label of the game. */
  title: Bilingual
  /** Words the game should draw its items from. */
  poolWordIds: number[]
}

export type ExamFormat =
  | 'listening-image'   // 听力: statement ↔ picture, true/false
  | 'reading-match'     // 阅读: sentence ↔ picture/answer
  | 'sentence-gap'      // 完成句子
  | 'order-sentence'    // 连词成句

export interface ExamStyleActivity extends ActivityBase {
  kind: 'exam-style'
  format: ExamFormat
  /** Instruction line, HSK-paper wording. */
  prompt: Bilingual
  /** Chinese stimulus — the statement, sentence or fragment. */
  stimulus: string
  stimulusPinyin: string
  question: MultipleChoice
}

export type Activity =
  | ExplanationActivity
  | WordIntroActivity
  | WordRecallActivity
  | HanziWriteActivity
  | ToneDiscriminateActivity
  | PinyinMatchActivity
  | PronounceActivity
  | ImageMatchActivity
  | GrammarBriefActivity
  | GrammarApplyActivity
  | SentenceOrderActivity
  | FillBlankActivity
  | TranslateActivity
  | RoleplayActivity
  | StoryExcerptActivity
  | DailyQaActivity
  | GameBreakActivity
  | ExamStyleActivity

/** All 18 kinds — the original 17 plus the explanation that now opens them. */
export const ACTIVITY_KINDS: ActivityKind[] = [
  'explanation',
  'word-intro',
  'word-recall',
  'hanzi-write',
  'tone-discriminate',
  'pinyin-match',
  'pronounce',
  'image-match',
  'grammar-brief',
  'grammar-apply',
  'sentence-order',
  'fill-blank',
  'translate',
  'roleplay',
  'story-excerpt',
  'daily-qa',
  'game-break',
  'exam-style',
]

/** Arabic label per kind — the pill above the activity card in the designs. */
export const ACTIVITY_KIND_LABEL_AR: Record<ActivityKind, string> = {
  explanation: 'شرح',
  'word-intro': 'كلمة جديدة',
  'word-recall': 'تذكّر الكلمة',
  'hanzi-write': 'اكتب الحرف',
  'tone-discriminate': 'ميّز النبرة',
  'pinyin-match': 'طابق البينين',
  pronounce: 'انطقها',
  'image-match': 'طابق الصورة',
  'grammar-brief': 'قاعدة سريعة',
  'grammar-apply': 'طبّق القاعدة',
  'sentence-order': 'رتّب الجملة',
  'fill-blank': 'أكمل الفراغ',
  translate: 'ترجم',
  roleplay: 'لعب دور',
  'story-excerpt': 'مقطع من قصة',
  'daily-qa': 'سؤال اليوم',
  'game-break': 'فاصل لعب',
  'exam-style': 'سؤال امتحان',
}

/**
 * English label per kind — the same pill, on `/en`. It sits BESIDE the Arabic
 * map rather than replacing it: `activity-engine.ts` and
 * `scripts/check-activities.js` both import `ACTIVITY_KIND_LABEL_AR` by name,
 * and this codebase keeps both languages at the call site on purpose.
 */
export const ACTIVITY_KIND_LABEL_EN: Record<ActivityKind, string> = {
  explanation: 'Explanation',
  'word-intro': 'New word',
  'word-recall': 'Recall the word',
  'hanzi-write': 'Write the character',
  'tone-discriminate': 'Spot the tone',
  'pinyin-match': 'Match the pinyin',
  pronounce: 'Say it',
  'image-match': 'Match the picture',
  'grammar-brief': 'Quick rule',
  'grammar-apply': 'Use the rule',
  'sentence-order': 'Order the sentence',
  'fill-blank': 'Fill the blank',
  translate: 'Translate',
  roleplay: 'Role-play',
  'story-excerpt': 'Story excerpt',
  'daily-qa': "Today's question",
  'game-break': 'Game break',
  'exam-style': 'Exam question',
}

/** The pill label for a kind, in the locale the route is serving. */
export function activityKindLabel(kind: ActivityKind, locale: 'ar' | 'en'): string {
  return locale === 'en' ? ACTIVITY_KIND_LABEL_EN[kind] : ACTIVITY_KIND_LABEL_AR[kind]
}

/**
 * A unit's title in the locale being served.
 *
 * Every screen used to render `unit.title` directly, which is the Arabic one,
 * so the English path listed an entire curriculum under Arabic headings. A
 * helper rather than a field access because there are six call sites and a
 * seventh will be added by someone who has not read this file.
 *
 * Falls back to the Arabic when `titleEn` is absent — unlike a sentence gloss,
 * a missing title cannot be dropped: a unit with no name is unnavigable, and a
 * name in the wrong language still tells the reader which unit it is.
 */
export function unitTitle(
  unit: { title: string; titleEn?: string },
  locale: 'ar' | 'en',
): string {
  if (locale !== 'en') return unit.title
  return unit.titleEn?.trim() || unit.title
}

// ── Learner state the engine reads ──────────────────────────────────────────

/**
 * The slice of learner state `buildActivityStream` needs. Deliberately a plain
 * structure, not the Zustand store, so the engine stays pure and testable.
 */
export interface LearnerState {
  /** SM-2 cards keyed by word id — `srsCards` from the store, as-is. */
  srsCards: Record<number, LearnerSrsCard>
  /** Units already completed, as `UnitKey`s. Drives review depth and unlock. */
  completedUnits: UnitKey[]
  /** Words the learner has answered wrong recently, most recent first. */
  missedWordIds: number[]
  /** Seed for the deterministic shuffles. Same seed ⇒ identical stream. */
  seed: number
}

/** Structural subset of `SRSCard` from `src/lib/srs.ts`. */
export interface LearnerSrsCard {
  wordId: number
  easeFactor: number
  interval: number
  repetitions: number
  nextReview: string | null
  lastReview: string | null
  reviewCount: number
  correctCount: number
}

export function emptyLearnerState(seed = 1): LearnerState {
  return { srsCards: {}, completedUnits: [], missedWordIds: [], seed }
}

// ── Tuning knobs (single source of truth for engine + validator) ────────────

export const UNIT_MIN_WORDS = 5
export const UNIT_MAX_WORDS = 8
/** A game-break lands roughly every this many activities. */
export const GAME_BREAK_EVERY = 6
/** No activity kind may appear this many times in a row. */
export const MAX_KIND_RUN = 3
