export type Section =
  | 'dashboard'
  | 'vocabulary'
  | 'pinyin'
  | 'hanzi'
  | 'lessons'
  | 'grammar'
  | 'conversations'
  | 'practice'
  | 'games'
  | 'stories'
  | 'exam'
  | 'chat'
  | 'roadmap'
  | 'sentences'
  | 'handwriting'
  | 'pronunciation'
